## Joining RI23 series sample IDs to ICPOES, IC, and stable isotope data

### - All data from Sharepoint Winter Watershed EMMA directory: https://uvmoffice.sharepoint.com/:f:/s/Winterwatershed/Em7xsXZomnFJvPg3qm5bpqcB0INgFeGMeJ8m_HdQfwu6Yg?e=9k32Up

### Sample IDs from Metadata/
- LCBP_RI23_sample-index-for-join.csv
        - A csv with the RI23 or ISO23 sample identifier and date/time/site/sample type

### Sample chemistry from LCBP-EMMA/
- LCBP_RI23_ic-for-join.csv
        - A csv with all RI23 ion chromatography results
        
- LCBP_RI23_icpoes-for-join.csv
        - A csv with all RI23 inductively coupled plasma optical emission spectroscopy results
        
- LCBP_RI23_isotope-for-join.csv
        - A csv with all RI23 stable water isotope results

In [1]:
import os
os.chdir("/home/millieginty/OneDrive/git-repos/EMMA/isco_metadata/LCBP_RI_sample_index")

!ls

LCBP_RI23_ic-for-join.csv	     RI23-IC-ICP-isotope-joined.csv
LCBP_RI23_icpoes-for-join.csv	     RI23-IC-ICP-isotope-joined_dups_pruned.csv
LCBP_RI23_isotope-for-join.csv	     RI23-isotope-joined.csv
LCBP_RI23_sample-index-for-join.csv

In [11]:
import pandas as pd

# Read CSV files with the 'Sample ID' column as the index
df_index = pd.read_csv('LCBP_RI23_sample-index-for-join.csv', index_col='Sample ID')
df_icpoes = pd.read_csv('LCBP_RI23_icpoes-for-join.csv', index_col='Sample ID')
df_ic = pd.read_csv('LCBP_RI23_ic-for-join.csv', index_col='Sample ID')
df_iso = pd.read_csv('LCBP_RI23_isotope-for-join.csv', index_col='Sample ID')

# Join the dataframes on the index ('Sample ID')
df_joined = df_index.merge(df_icpoes, left_index=True, right_index=True, how='left')
df_joined = df_joined.merge(df_ic, left_index=True, right_index=True, how='left')
df_joined = df_joined.merge(df_iso, left_index=True, right_index=True, how='left')

# Save the joined dataframe to a new CSV file
df_joined.to_csv('RI23-IC-ICP-isotope-joined.csv')

# Print the first few rows of the joined dataframe
df_joined.head(20)

,Site,Date,Time,Type,Type2,Index-notes,ICP-notes,Fe_mg_L,Mn_mg_L,Cu_mg_L,...,NO2_mg_L,Br_mg_L,NO3_mg_L,PO4_mg_L,SO4_mg_L,IC-notes,NRS_LWIA_notes,dD,d18O,iso-notes
Sample ID,,,,,,,,,,,,,,,,,,,,,
RI23-1001,Hungerford,02/9/2023,13:40,Grab/Isco,Stream,need to verify type,NaN,0.070703,0.065630,0.000484,...,NaN,NaN,13.797849,NaN,50.594685,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-66.095,-9.827,NaN
RI23-1002,Hungerford,02/9/2023,16:00,Grab/Isco,Stream,need to verify type,NaN,0.066423,0.068312,-0.000213,...,0.793568,NaN,13.732435,NaN,48.186849,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-66.847,-9.862,NaN
RI23-1003,Hungerford,02/9/2023,22:00,Grab/Isco,Stream,need to verify type,NaN,0.082407,0.052984,-0.000072,...,0.793552,NaN,12.650178,NaN,45.782770,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-67.317,-9.800,NaN
RI23-1004,Hungerford,02/10/2023,4:00,Grab/Isco,Stream,need to verify type,NaN,NaN,NaN,NaN,...,NaN,NaN,12.132705,1.608651,19.336434,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-72.393,-10.536,NaN
RI23-1005,Hungerford,02/10/2023,10:00,Grab/Isco,Stream,need to verify type,NaN,0.059852,0.036705,0.000798,...,0.794759,NaN,11.792564,1.597842,33.673348,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-78.866,-11.598,NaN
RI23-1006,Wade,02/10/2023,13:00,Grab/Isco,Stream,need to verify type,NaN,NaN,NaN,NaN,...,NaN,NaN,2.633325,1.593013,6.720394,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-80.253,-12.024,NaN
RI23-1007,Hungerford,02/10/2023,16:00,Grab/Isco,Stream,need to verify type,NaN,0.082126,0.033195,0.002214,...,0.794017,NaN,11.882055,1.602656,16.175028,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-80.652,-11.977,NaN
RI23-1008,Hungerford,02/11/2023,12:30,Grab/Isco,Stream,need to verify type,NaN,0.074341,0.017435,0.001111,...,NaN,NaN,17.577501,NaN,27.169938,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-75.973,-11.294,NaN
RI23-1009,Wade,02/15/2023,15:00,Grab/Isco,Stream,need to verify type,NaN,-0.000368,-0.013919,0.000669,...,NaN,NaN,2.365148,NaN,8.192964,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-78.421,-11.844,NaN
RI23-1010,Wade,02/15/2023,19:00,Grab/Isco,Stream,need to verify type,NaN,0.015831,-0.000335,-0.001384,...,NaN,NaN,2.337741,NaN,8.039080,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-78.932,-11.876,NaN
RI23-1011,Wade,02/15/2023,23:00,Grab/Isco,Stream,need to verify type,NaN,0.015128,-0.000223,-0.001005,...,NaN,NaN,2.370623,1.604952,7.654233,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-79.978,-12.027,NaN
RI23-1012,Wade,02/16/2023,3:00,Grab/Isco,Stream,need to verify type,NaN,0.009929,-0.005332,-0.000276,...,NaN,NaN,2.335432,1.596833,7.121828,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-81.829,-12.071,NaN
RI23-1013,Wade,02/16/2023,7:00,Grab/Isco,Stream,need to verify type,NaN,NaN,NaN,NaN,...,NaN,NaN,2.380358,1.599587,6.799209,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-83.418,-12.430,NaN
RI23-1014,Wade,02/16/2023,11:00,Grab/Isco,Stream,need to verify type,NaN,0.006730,-0.013613,-0.000215,...,NaN,1.564433,2.427249,1.600098,6.946511,2024-10-03 MED switched SO4 and PO4 values bec...,NaN,-82.863,-12.350,NaN
RI23-1020,NaN,NaN,NaN,NaN,Stream,no info only ICP log,NaN,0.094635,0.034331,-0.000383,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RI23-1025,Wade,02/15/2023,12:00,Grab,Stream,need to verify type,NaN,0.016032,0.004307,-0.001299,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-78.111,-11.784,NaN
RI23-1026,Hungerford,02/15/2023,14:00,Grab/Isco,Stream,need to verify type,NaN,NaN,NaN,NaN,...,NaN,NaN,25.219200,1.623300,24.582400,There is no 33 - though there are 2 34s,NaN,-71.186,-10.577,NaN
RI23-1027,Hungerford,02/16/2023,10:30,Grab/Isco,Stream,need to verify type,NaN,0.090110,0.009450,0.000992,...,0.416300,NaN,15.731900,1.613000,17.484100,NaN,NaN,-74.385,-11.008,NaN
RI23-1028,Wade,02/16/2023,14:00,Grab/Isco,Stream,need to verify type,NaN,0.000784,-0.000537,-0.001339,...,0.416800,NaN,2.017700,NaN,3.335800,NaN,NaN,-82.344,-12.322,NaN
RI23-1029,Wade,02/16/2023,20:00,Grab/Isco,Stream,need to verify type,NaN,-0.012384,-0.008663,-0.000313,...,NaN,NaN,1.693300,NaN,3.332100,NaN,NaN,-82.319,-12.330,NaN

In [12]:
print("Index duplicates:", df_index.index.duplicated().sum())
print("ICPOES duplicates:", df_icpoes.index.duplicated().sum())
print("IC duplicates:", df_ic.index.duplicated().sum())
print("Isotope duplicates:", df_iso.index.duplicated().sum())

Index duplicates: 0
ICPOES duplicates: 0
IC duplicates: 0
Isotope duplicates: 0